### ISSUE TITLE
forms does not create/save when dtRowID in tables.json 

### ISSUE THREAD

**Issue by whizzly** [laravel-enso/forms#80] opened 2020-03-29 12:01 UTC
This is  a **bug request**.

[ *] Are you running the latest version?  3.9
[ *] Are you reporting to the correct repository?
[ *] Did you check the documentation?
[ *] Did you perform a cursory search?

### Description

When i configure a individual dtRowId in my tables json-template, that works in the tables.
that was explained here: https://github.com/laravel-enso/enso/issues/286
### Steps to Reproduce

1. with enso, i generate a new model with files and structure
2. i use an indivual dtRowId like described in the above issue 286
3. that works fine in the tables
4. i click on the create --> the form opens
5. i click on save --> "something went wrong ..."

### Expected behavior
saving correct
### Actual behavior
"something went wrong"
the laravel log show in this moment always the same:
SQLSTATE[42703]: Undefined column: 7 ERROR:  column \"id\" does not exist
LINE 1: ... \"dogs\" (\"name\", \"bemerkung\") values ($1, $2) returning \"id\"

when i try to edit a existing record, i get an:
Error: Route Error: "cat" key is required for route "cats.edit"
in the developer tools from chrome or firefox

For me the question is: how can i configure that forms knows, that there is another id - dtRowId (for forms)

**Comment by aocneanu** [comment] 2020-03-29 16:16
I'm not sure I understand the issue but this does not appear to be a bug.

Did you write the backend logic for the request validator, model etc?

You have lots of examples across enso with functional tables / forms. Make sure you at least replicate that.

**Comment by whizzly** [comment] 2020-03-29 16:28
i tried that multiple times. with the correct backend logic. I had an excellent step by step manual from @gandesc here: https://github.com/laravel-enso/enso/issues/280
when i let all with the standard id, that works fine. when i follow your suggestion from here:
https://github.com/laravel-enso/enso/issues/286
that works for the tables part, but not for the forms part

**Comment by aocneanu** [comment] 2020-03-29 16:35
Post here the request payload (chrome console, the post request, get the payload from the headers tab, scroll to bottom)

**Comment by whizzly** [comment] 2020-03-29 17:07
```
{cat_id: "5", name: "Maunz", bemerkung: "Katze ... weiß", created_at: "", updated_at: "",…}
cat_id: "5"
name: "Maunz"
bemerkung: "Katze ... weiß"
created_at: ""
updated_at: ""
_params: null
```
and the associated preview:
{,…}
message: "SQLSTATE[42703]: Undefined column: 7 ERROR:  column "id" does not exist↵LINE 1: ... "cats" ("name", "bemerkung") values ($1, $2) returning "id"↵                                                                   ^ (SQL: insert into "cats" ("name", "bemerkung") values (Maunz, Katze ... weiß) returning "id")"
exception: "Illuminate\Database\QueryException"
file: "/var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php"
line: 669
trace: [{file: "/var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php", line: 629,…},…]

**Comment by whizzly** [comment] 2020-03-29 17:16
```
{
    "name": "Cat",
    "routePrefix": "cats",
    "dtRowId": "cats.cat_id",
    "crtNo": true,
```
that is the corresponding part from cats.json in .../app/Tables/Templates/cats.json

**Comment by aocneanu** [comment] 2020-03-29 17:45
And the Model / persist logic

**Comment by whizzly** [comment] 2020-03-29 18:45
model
`<?php

namespace App\Model;

use Illuminate\Database\Eloquent\Model;
use LaravelEnso\Tables\App\Traits\TableCache;

class Cat extends Model
{
	use TableCache;
    public $timestamps = false;
    protected $fillable = [
        'name', 'bemerkung'
    ];
    //
}`
Validate:
`<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ValidateCatRequest extends FormRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
            'cat_id' => 'nullable',
            'name' => 'nullable',
            'bemerkung' => 'nullable'
            //
        ];
    }
}`

**Comment by whizzly** [comment] 2020-03-31 01:15
Seems, as this would be a fundamental problem. I have the same behaviour when i klick on the edit button of the administration group or on the administrator itself ...
maybe a mistake in the installation

**Comment by whizzly** [comment] 2020-03-31 01:38
just made a fresh installation
now it works
I apologize for the inconvenience

**Comment by whizzly** [comment] 2020-03-31 16:51
sorry, but after correcting the installation - the problem with the dtRowId is like before.
the installation corrected the problem only for the administration group and the administrator.
but if you use an own dtRowId for models generated with the cli ... forms does not work, all is like described

**Comment by aocneanu** [comment] 2020-03-31 17:49
Please upload everything in a repo I can clone and I will look at it.

**Comment by whizzly** [comment] 2020-03-31 17:53
thx, i wanny try to do that

**Comment by whizzly** [comment] 2020-03-31 18:46
i uploaded it to my orginal project that i will try to renew with enso. it is placed in sourceforge.
Unfortunately all your Readme.md stuff and anything else is within. I will delete it directly if you cloned it. 
https://sourceforge.net/p/ensovet/code/ci/master/tree/
it is with a postgres db in the .env ...

**Comment by aocneanu** [comment] 2020-04-02 06:07
The problem you're encountering has nothing to do with Enso.

You decided to customize the primary key in the dogs table but forgot the read the docs [https://laravel.com/docs/7.x/eloquent#eloquent-model-conventions]

The problem is fixed by adding a `protected $primaryKey = 'dog_id'` in your Dog model.

A few advices:

- start playing with a framework (like Laravel) by not customizing things. Read the docs carefully instead, then learn and understand the conventions, use them until you really figure out the framework and then customize whatever you believe that the majority is using wrong.
- move on with Enso only after understanding well at least how Laravel works.
- customize Enso's frontend after understanding how Vue works

**Closed by aocneanu** 2020-04-02 06:07 UTC

**Comment by whizzly** [comment] 2020-04-02 06:45
Basically, you are right.
And the following sentences are only intended to explain the circumstances,
but are not an excuse.
My problem is the time that I do it as a part-time job.
I have read and implemented the documentation, but that was a year ago. You
could see this on three other models, since the protected $ primarykey is
already entered (not yet uploaded).
In this case it was unfortunately a stupid mistake, because I wanted to do
a basic test in a new environment. And I didn't get the idea that there is
a relationship between the "protected $ primarykey" entry and the dtRowId.
A minimal hint in the documentation would have helped.
I'm sorry to have wasted your time. At this point I can only offer to
either help with the documentation. Or to let you participate in the
project when it is implemented.
I don't have the time to fully internationalize it, but maybe translate it
into English.
That might be the case in two years.
Once again many thanks
Whizzly

Adrian Ocneanu <notifications@github.com> schrieb am Do., 2. Apr. 2020,
08:08:

**Comment by aocneanu** [comment] 2020-04-02 08:25
>And I didn't get the idea that there is
a relationship between the "protected $ primarykey" entry and the dtRowId.

For the third time, it has nothing to do with enso / tables / dtRowId

The problem in your case is that by forgeting to set the customized primary key you broke Laravel's route model binding, also [documented](https://laravel.com/docs/7.x/routing#route-model-binding).

That means that whenever you would try `project.test/vs/cats/1/edit` and expecting to resolve a model using laravel route model binding `__invoke(Cat $cat)` what Laravel does is try to fetch from the database a model of class Cat with the `id` (the cat model's primary key) of 1.

This would happen even if the table or form package was not installed in your project.

>A minimal hint in the documentation would have helped

I guess you realize (now) too that's not the case. What I did instead I suggested that you should really get friendly with Laravel basics. Route model binding is just another Laravel 101.

>I'm sorry to have wasted your time

You don't have to because I'm that one that offered to help. Also if you would take the sincere advices I gave in the spirit that I gave them than it would mean that I did help you after all.

If instead you are offended by my advices than just ignore them.

**Comment by whizzly** [comment] 2020-04-02 10:49
this is a misunderstanding because my english is so bad. I am not offended.
I am grateful for the information and I promise to observe it. I will
improve myself

Adrian Ocneanu <notifications@github.com> schrieb am Do., 2. Apr. 2020,
10:26:
